[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rapido_intelligent_system"
version = "0.0.1"
description = "Build dashboard and predictive models using rapido datasets"
authors = [
  { name = "kittu" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "gdown>=6.1.0",
    "loguru",
    "marimo>=0.23.10",
    "mkdocs",
    "nbformat>=5.11.1",
    "pip",
    "pydantic-ai>=2.32.1",
    "python-dotenv",
    "rich>=15.0.0",
    "tqdm",
    "typer",
]
requires-python = "~=3.14.0"


[tool.ruff]
line-length = 99
src = ["rapido_intelligent_system"]
include = ["pyproject.toml", "rapido_intelligent_system/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["rapido_intelligent_system"]
force-sort-within-sections = true

[tool.marimo.runtime]
watcher_on_save = "autorun"


[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true

[dependency-groups]
dev = [
    "altair>=6.2.2",
    "catboost>=1.2.10",
    "commitizen>=4.16.3",
    "lightgbm>=4.6.0",
    "numpy>=2.4.6",
    "polars>=1.44.1",
    "ruff>=0.15.18",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "ty>=0.0.51",
    "xgboost>=3.3.0",
]
